/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as HiraganaRouteImport } from './routes/hiragana'
import { Route as KanjiRouteImport } from './routes/kanji'
import { Route as KatakanaRouteImport } from './routes/katakana'
import { Route as LicoesRouteImport } from './routes/licoes'
import { Route as RevisaoRouteImport } from './routes/revisao'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as LicoesIndexRouteImport } from './routes/licoes.index'
import { Route as LicoesIdRouteImport } from './routes/licoes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const HiraganaRoute = HiraganaRouteImport.update({
  id: '/hiragana',
  path: '/hiragana',
  getParentRoute: () => rootRouteImport,
} as any)
const KanjiRoute = KanjiRouteImport.update({
  id: '/kanji',
  path: '/kanji',
  getParentRoute: () => rootRouteImport,
} as any)
const KatakanaRoute = KatakanaRouteImport.update({
  id: '/katakana',
  path: '/katakana',
  getParentRoute: () => rootRouteImport,
} as any)
const LicoesRoute = LicoesRouteImport.update({
  id: '/licoes',
  path: '/licoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisaoRoute = RevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const LicoesIndexRoute = LicoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LicoesRoute,
} as any)
const LicoesIdRoute = LicoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LicoesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/flashcards': typeof FlashcardsRoute
  '/hiragana': typeof HiraganaRoute
  '/kanji': typeof KanjiRoute
  '/katakana': typeof KatakanaRoute
  '/licoes': typeof LicoesRouteWithChildren
  '/revisao': typeof RevisaoRoute
  '/api/tts': typeof ApiTtsRoute
  '/licoes/$id': typeof LicoesIdRoute
  '/licoes/': typeof LicoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/flashcards': typeof FlashcardsRoute
  '/hiragana': typeof HiraganaRoute
  '/kanji': typeof KanjiRoute
  '/katakana': typeof KatakanaRoute
  '/revisao': typeof RevisaoRoute
  '/api/tts': typeof ApiTtsRoute
  '/licoes/$id': typeof LicoesIdRoute
  '/licoes': typeof LicoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/flashcards': typeof FlashcardsRoute
  '/hiragana': typeof HiraganaRoute
  '/kanji': typeof KanjiRoute
  '/katakana': typeof KatakanaRoute
  '/licoes': typeof LicoesRouteWithChildren
  '/revisao': typeof RevisaoRoute
  '/api/tts': typeof ApiTtsRoute
  '/licoes/$id': typeof LicoesIdRoute
  '/licoes/': typeof LicoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conta'
    | '/flashcards'
    | '/hiragana'
    | '/kanji'
    | '/katakana'
    | '/licoes'
    | '/revisao'
    | '/api/tts'
    | '/licoes/$id'
    | '/licoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conta'
    | '/flashcards'
    | '/hiragana'
    | '/kanji'
    | '/katakana'
    | '/revisao'
    | '/api/tts'
    | '/licoes/$id'
    | '/licoes'
  id:
    | '__root__'
    | '/'
    | '/conta'
    | '/flashcards'
    | '/hiragana'
    | '/kanji'
    | '/katakana'
    | '/licoes'
    | '/revisao'
    | '/api/tts'
    | '/licoes/$id'
    | '/licoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContaRoute: typeof ContaRoute
  FlashcardsRoute: typeof FlashcardsRoute
  HiraganaRoute: typeof HiraganaRoute
  KanjiRoute: typeof KanjiRoute
  KatakanaRoute: typeof KatakanaRoute
  LicoesRoute: typeof LicoesRouteWithChildren
  RevisaoRoute: typeof RevisaoRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiragana': {
      id: '/hiragana'
      path: '/hiragana'
      fullPath: '/hiragana'
      preLoaderRoute: typeof HiraganaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanji': {
      id: '/kanji'
      path: '/kanji'
      fullPath: '/kanji'
      preLoaderRoute: typeof KanjiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katakana': {
      id: '/katakana'
      path: '/katakana'
      fullPath: '/katakana'
      preLoaderRoute: typeof KatakanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licoes': {
      id: '/licoes'
      path: '/licoes'
      fullPath: '/licoes'
      preLoaderRoute: typeof LicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisao': {
      id: '/revisao'
      path: '/revisao'
      fullPath: '/revisao'
      preLoaderRoute: typeof RevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licoes/': {
      id: '/licoes/'
      path: '/'
      fullPath: '/licoes/'
      preLoaderRoute: typeof LicoesIndexRouteImport
      parentRoute: typeof LicoesRoute
    }
    '/licoes/$id': {
      id: '/licoes/$id'
      path: '/$id'
      fullPath: '/licoes/$id'
      preLoaderRoute: typeof LicoesIdRouteImport
      parentRoute: typeof LicoesRoute
    }
  }
}

interface LicoesRouteChildren {
  LicoesIdRoute: typeof LicoesIdRoute
  LicoesIndexRoute: typeof LicoesIndexRoute
}

const LicoesRouteChildren: LicoesRouteChildren = {
  LicoesIdRoute: LicoesIdRoute,
  LicoesIndexRoute: LicoesIndexRoute,
}

const LicoesRouteWithChildren =
  LicoesRoute._addFileChildren(LicoesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContaRoute: ContaRoute,
  FlashcardsRoute: FlashcardsRoute,
  HiraganaRoute: HiraganaRoute,
  KanjiRoute: KanjiRoute,
  KatakanaRoute: KatakanaRoute,
  LicoesRoute: LicoesRouteWithChildren,
  RevisaoRoute: RevisaoRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
